### ISSUE TITLE
Qaterial Online slowing browser

### ISSUE THREAD

**Issue by Daguerreo** [OlivierLDff/Qaterial#25]
Hi, sorry if this is not the right place for the issue, but I didn't find the issue section in QaterialOnline.
Since yesterdey, when loading QaterialOnline in both Chrome on Windows and Firefox on Linux I'm receving a message of page not responding/page is slowing down, and it's not possibile anymore to use it.

**Comment by Daguerreo** [comment]
QmlOnline page is loading properly instead, so it's not related with browser or connection

**Comment by OlivierLDff** [comment]
I can reproduce it. I will investigate.

**Comment by OlivierLDff** [comment]
Fix in e7b82542fd53a73eaeebf84cde3d8e789be1a18f
This was cause by a singleton file importing Qaterial. Causing an infinite loop, and resulting in application never loading.
I think this is a Qt bug with wasm because it's not present in desktop.

Anyway, if QaterialOnline is down again, then you might want to have a look at https://olivierldff.github.io/Qaterial/QaterialHotReload.html
That allow you to do hot reload on desktop.

[](https://user-images.githubusercontent.com/17255804/85396672-6c787200-b552-11ea-814e-12ae2c6db0e9.gif)

**Comment by Daguerreo** [comment]
Fixed, thank you. If you think it's a wasm bug, maybe should be useful to report to Qt...

**Comment by OlivierLDff** [comment]
I think they are aware of it : https://bugreports.qt.io/browse/QTBUG-49370
